### ISSUE TITLE
看着很酷

### ISSUE THREAD

**Issue by 025nju** [ChinaLike/TagTextView#1]
Java项目里能用吗？若能用，可以指导下怎么用吗。谢谢。

**Comment by ChinaLike** [comment]
可以使用的，在Wiki里的文档里面，最下方有java和kotlin的使用范例，或者demo里面也有！

**Comment by ChinaLike** [comment]
可以使用的，在Wiki里的文档里面，最下方有java和kotlin的使用范例，或者demo里面也有！
