### ISSUE TITLE
因为有 verifytext mvvm情况下绑定很不好使用

### ISSUE THREAD

**Issue by Gowa2017** [ChinaLike/TagTextView#12]
如题 必须要先设置文本在绑定  应该加上默认值更好

**Comment by ChinaLike** [comment]
很遗憾，我尝试着去做修改，但是单个标签没啥问题，但是一个文本多个标签就有问题。所以建议还是先设置文本在做tag，mvvm中可以尝试用扩展方法来处理，暂时不要在xml中绑定数据。后期我在想办法优化一下
