### ISSUE TITLE
如何移除tag呢？

### ISSUE THREAD

**Issue by MasterMvp** [ChinaLike/TagTextView#16]
应用于adapter中，如果是addtag的话，item复用时，会不断地添加新的标签
另一种场景，当前标签设置了一种，想要换成另一种该如何写？使用replaceTag填写标签文本内容不会替换，填写text展示内容，会把text替换成标签

**Comment by ChinaLike** [comment]
在adapter中只要在适配器中按照正常流程，设置text文本后，在设置标签是没问题的。
同理，当设置标签后需要变化成另外一种标签，重走一遍流程即可：设置文本、设置替换标签
