### ISSUE TITLE
提个意见 换行时...

### ISSUE THREAD

**Issue by GuangNian10000** [ChinaLike/TagTextView#2]
换行时 如果图片或标签前面没有文字就提前换行？
例：
  1.
  文本文本文本文本文本
  图片
  2.
  文本文本文本文本文
  本图片

单个图片在第二行影响美观

**Comment by ChinaLike** [comment]
感谢您的宝贵意见，我尝试着弄一下吧！

**Comment by bosscai** [comment]
你好楼主，tvt_background_color能否尝试考虑加入drawable文件

**Comment by ChinaLike** [comment]
> 你好楼主，tvt_background_color能否尝试考虑加入drawable文件

新版本已经加入，其次可以考虑使用自定义View也可以实现
