### ISSUE TITLE
点击事件问题

### ISSUE THREAD

**Issue by ZhiQiangCoding** [ChinaLike/TagTextView#4]
大佬，指定文本点击事件可以加一个不需要设置颜色的吗

**Comment by ZhiQiangCoding** [comment]
点击事件这里必须依赖kotlin包，能否扩展下（ new Function0<Unit>()）

**Comment by ChinaLike** [comment]
> 
先更新到最新版本

不设置颜色，增加点击事件，有以下两种方法：
+ 使用setUnderline方法，但是有下划线
+ 使用setSpecificTextColor方法，颜色设置成文本颜色

**Comment by ChinaLike** [comment]
> 点击事件这里必须依赖kotlin包，能否扩展下（ new Function0()）

这个本来是Kotlin工程，如果你实在不想依赖Kotlin包，但插件必须安装，在工程下的build.gradle

```
buildscript {
    ext.kotlin_version = "x.x.x"
    ...
    dependencies {
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        ...
    }
}
```

**Comment by ChinaLike** [comment]
先更新到最新版本,看能不能满足

**Comment by Fomovet** [comment]
@ChinaLike 请教一下大佬，在Java版中图片类型的(Type.TEXT_IMAG )Tag点击事件怎么监听？

**Comment by ChinaLike** [comment]
> @ChinaLike 请教一下大佬，在Java版中图片类型的(Type.TEXT_IMAG )Tag点击事件怎么监听？

在最新版本中已经添加了点击事件
