### ISSUE TITLE
左右两边设置文字和图片怎么办?

### ISSUE THREAD

**Issue by MasterMvp** [ChinaLike/TagTextView#6]
[文字标签] 文本文本文本[图片标签]
文本文本文本文本文本文本文本文
本文本文本文本文本文本

这样的效果该如何处理?

**Comment by ChinaLike** [comment]
> [文字标签] 文本文本文本[图片标签] 文本文本文本文本文本文本文本文 本文本文本文本文本文本
> 
> 这样的效果该如何处理?

你说的是像第一行，前面是文字标签，后面是图片标签，图片标签完了就换行吗？

**Comment by ChinaLike** [comment]
> [文字标签] 文本文本文本[图片标签] 文本文本文本文本文本文本文本文 本文本文本文本文本文本
> 
> 这样的效果该如何处理?

如果单纯是混合标签，调用两次addTag方法就行，设置好下标
